# Generated by Django 3.0.3 on 2020-02-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concoreapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=50)),
                ('Nome', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=20)),
                ('CPF', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='company',
            new_name='Empresa',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='fantasy',
            new_name='Fantasia',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='owner',
            new_name='Responsavel',
        ),
    ]
