# Generated by Django 3.0.3 on 2020-03-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concoreapi', '0003_auto_20200302_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Responsavel',
            new_name='Responsável',
        ),
    ]
